site_name: Visual Analytics - Documentation
site_url: https://docs.berlin-united.com/

nav:
  - 'index.md'
  - LogCrawler:
    - 'logcrawler/index.md'
    - 'logcrawler/logstructure.md'
  - Visual Analytics:
    - 'vat/index.md'
    - 'vat/dev_setup_k8s.md'
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode