[project]
site_name = "Visual Analytics - Documentation"
site_url = "https://docs-staging.berlin-united.com/"
extra_css = ["stylesheets/extra.css"]

extra_javascript = [
    "javascripts/mathjax.js",
    "https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js"
]

nav = [
  {"Home" = [
      {"Welcome to Berlin United" = "index.md"},
      {"Getting Started" = [
         {"Intial Setup" = "getting_started/setup.md"},
         {"Working with a Robot" = "getting_started/robot.md"},
      ]},
      {"Basics" = [
         {"Handling the NAO" = "basics/nao_handling.md"},
         {"Handling the Booster" = "basics/booster_handling.md"},
         {"Nao Calibration" = "basics/nao_calibration.md"},
      ]},
      {"Architecture" = [
         {"Overview" = "architecture/overview.md"},
      ]},
      {"Perception" = [
         {"Overview" = "perception/overview.md"},
      ]},
      {"Modeling" = [
         {"Overview" = "modeling/overview.md"},
      ]},
      {"Behavior" = [
         {"Overview" = "behavior/overview.md"},
      ]},
      {"Motion Control" = [
         {"Overview" = "motion/overview.md"},
      ]},
      {"Tools" = [
         {"Overview" = "tools/overview.md"},
      ]},
      {"Bibliography" = "bibliography.md"},

  ]},
  {"Visual Analytics" = [
     "vat/index.md",
     "vat/user_management.md",
     {"Logcrawler" = "vat/logcrawler.md"},
     {"Log Structure" = "vat/logstructure.md"},
     "vat/dev.md",
     {"Developer Setup" = [
     "dev/index.md",
     "dev/local_k8s.md",
     "dev/local_postgres.md",
  ]},
  ]},
  {"Labelstudio" = [
     "annotations/index.md",
  ]}
]

[project.theme]
features = [
    "navigation.tabs",
    "navigation.tabs.sticky",
    "toc.follow",
]

[[project.theme.palette]]
scheme = "default"
primary = "pink"
accent = "pink"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
primary = "purple"
accent = "purple"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.markdown_extensions.pymdownx.arithmatex]
generic = true

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true

[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.snippets]
[project.markdown_extensions.pymdownx.superfences]

